<a href="https://colab.research.google.com/github/Valentorlasco/BIG-DATA/blob/main/Python_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Big Data
Estructuras de control y funciones clásicas

### 1) Nuestro amigo el **IF**

In [2]:
nro_de_cliente=999

if nro_de_cliente==999:
  print('es el cliente 999!!')
else:
  print('cliente no encontrado :(')

es el cliente 999!!


In [3]:
nro_de_cliente=111

In [4]:
# if anidado
if nro_de_cliente==999:
  print('es el cliente 999!!')
elif nro_de_cliente==111:
  print('es el cliente 111!!')
else:
  print('cliente no encontrado :(')

es el cliente 111!!


Igual: x1 == x2

Distinto: x1 != x2

Menor a: x1 < x2

Menor o igual a: x1 <= x2

Mayor a: x1 > x2

Mayor o igual x1 >= x2



### 2) *Mientras* vemos el `while`

In [ ]:
# imprimir 3 elementos
i=0
while(i<3):
  i=i+1
  print(i)

1
2
3


In [ ]:
# bucle infinito
while(1):
  x1=input('¿Nombre? ')

  if x1=='me aburri':
    break

  print('Bienvenido! ' + x1)


¿Nombre? valentino
Bienvenido! valentino
¿Nombre? facundo
Bienvenido! facundo
¿Nombre? me aburii
Bienvenido! me aburii
¿Nombre? me aburri


### 3) *Para* que usar while, si hay `for`!

In [5]:
lista=[1,2,3,4]

In [6]:
for i in lista:

  if i == 3:
    break

  print(i)

1
2


¿Cómo usar for sobre pandas data frame?

In [7]:
import pandas as pd

d_star_wars=pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/fpineyro/homework-0/master/starwars.csv", sep=',')
d_star_wars.head()


name  height mass hair_color   skin_color eye_color birth_year  \
0  Luke Skywalker   172.0   77      blond         fair      blue      19BBY   
1           C-3PO   167.0   75        NaN         gold    yellow     112BBY   
2           R2-D2    96.0   32        NaN  white, blue       red      33BBY   
3     Darth Vader   202.0  136       none        white    yellow    41.9BBY   
4     Leia Organa   150.0   49      brown        light     brown      19BBY   

   gender homeworld species  
0    male  Tatooine   Human  
1     NaN  Tatooine   Droid  
2     NaN     Naboo   Droid  
3    male  Tatooine   Human  
4  female  Alderaan   Human

In [8]:
# no hacer así
for row in d_star_wars:
  print(row)



name
height
mass
hair_color
skin_color
eye_color
birth_year
gender
homeworld
species


In [9]:
# Usar iterrows()

for label, row in d_star_wars[:5].iterrows():
  print('El label es: ' + str(label))
  print(row)

El label es: 0
name          Luke Skywalker
height                 172.0
mass                      77
hair_color             blond
skin_color              fair
eye_color               blue
birth_year             19BBY
gender                  male
homeworld           Tatooine
species                Human
Name: 0, dtype: object
El label es: 1
name             C-3PO
height           167.0
mass                75
hair_color         NaN
skin_color        gold
eye_color       yellow
birth_year      112BBY
gender             NaN
homeworld     Tatooine
species          Droid
Name: 1, dtype: object
El label es: 2
name                R2-D2
height               96.0
mass                   32
hair_color            NaN
skin_color    white, blue
eye_color             red
birth_year          33BBY
gender                NaN
homeworld           Naboo
species             Droid
Name: 2, dtype: object
El label es: 3
name          Darth Vader
height              202.0
mass                  136
hair_color   

Accediendo a cada valor:

In [10]:
for _, row in d_star_wars[:10].iterrows():
  print('Personaje: ' + row['name'] + ' lugar ' + row['homeworld'])

Personaje: Luke Skywalker lugar Tatooine
Personaje: C-3PO lugar Tatooine
Personaje: R2-D2 lugar Naboo
Personaje: Darth Vader lugar Tatooine
Personaje: Leia Organa lugar Alderaan
Personaje: Owen Lars lugar Tatooine
Personaje: Beru Whitesun lars lugar Tatooine
Personaje: R5-D4 lugar Tatooine
Personaje: Biggs Darklighter lugar Tatooine
Personaje: Obi-Wan Kenobi lugar Stewjon


### 4) ¿Cómo crear funciones en Python?

In [11]:
def mi_funcion():
  print('hola mundo')

In [12]:
mi_funcion()

hola mundo


¿Cómo crear una función con parámetros?

In [13]:
def sumar(valor1, valor2):
  return valor1+valor2

In [14]:
sumar(valor1 = 5, valor2=5)

10

¿Cómo explorar el contenido de una función?

In [15]:
%%capture
!pip install funpymodeling

In [16]:
from funpymodeling.exploratory import status

In [17]:
status(d_star_wars)

variable  q_nan     p_nan  q_zeros  p_zeros  unique     type
0        name      0  0.000000        0      0.0      87   object
1      height      6  0.068966        0      0.0      45  float64
2        mass     28  0.321839        0      0.0      38   object
3  hair_color      6  0.068966        0      0.0      11   object
4  skin_color      2  0.022989        0      0.0      30   object
5   eye_color      3  0.034483        0      0.0      14   object
6  birth_year     44  0.505747        0      0.0      36   object
7      gender      3  0.034483        0      0.0       4   object
8   homeworld     10  0.114943        0      0.0      48   object
9     species      5  0.057471        0      0.0      37   object

In [18]:
#calcula la cantidad de valores únicos presentes en cada columna del DataFrame.
d_star_wars.nunique().values

array([87, 45, 38, 11, 30, 14, 36,  4, 48, 37])

In [19]:
d_star_wars.columns

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'gender', 'homeworld', 'species'],
      dtype='object')

In [20]:
def status2(data):
  return pd.DataFrame({'variables': data.columns, 'valores_unicos':data.nunique().values})

In [21]:
status2(d_star_wars)

variables  valores_unicos
0        name              87
1      height              45
2        mass              38
3  hair_color              11
4  skin_color              30
5   eye_color              14
6  birth_year              36
7      gender               4
8   homeworld              48
9     species              37

<br>

---



# C.2.1) ¿Qué es `numpy`?

In [22]:
import numpy as np

In [23]:
arr1=np.array([1,2,3,4,5])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [25]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [26]:
arr1.shape # ranking 1

(5,)

¿Cómo crear un "tabla" en numpy?

Rank 2 array / 2D

In [27]:
arr2=np.array([[1,2,3,4,5], [9,8,7,6,5]])

arr2

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [28]:
arr2.shape

(2, 5)

Rank 3 array / 3D

In [29]:
arr3=np.array([[[1,2,3,4,5], [9,8,7,6,5]]])

In [30]:
arr3.shape

(1, 2, 5)

### C.2.2) ¿Cómo hacer `reshape` en numpy?

In [31]:
arr3=np.array([1,2,3,4,5,6])
print(arr3)
print(arr3.shape)

[1 2 3 4 5 6]
(6,)


In [32]:
arr4=arr3.reshape((2,3))

arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr4.shape

(2, 3)

¿Cómo hacer flatten de un numpy array?

In [34]:
arr5=arr4.flatten()
arr5

array([1, 2, 3, 4, 5, 6])

### C.2.3) ¿Cómo hacer slice de numpy?

In [35]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
# 1er elemento
arr1[0]

1

In [37]:
arr1[0:3]

array([1, 2, 3])

### C.2.4) ¿Cómo acceder a arrays n-dimensionales?

In [38]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr4[0,:]

array([1, 2, 3])

In [40]:
arr4[1,0]

4

In [41]:
arr4[1,0:2]

array([4, 5])

In [42]:
# acceder a toda la 1er dimensión
arr4[0]

array([1, 2, 3])

Imagen resumen numpy

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="300px">

[Fuente](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html).

#Ejercicios

Ejercicio 1: Crear un if anidado para verificar si el numero de cliente está entre 0 y 4, le decimos 'usuario autorizado' en cualquier otro caso indicar 'usuario no autorizado'.

In [43]:
#Ejercicio 1

if nro_de_cliente>=0 and nro_de_cliente<=4:
  print('usuario autorizado')
else:
  print('usuario no autorizado')

usuario no autorizado


Ejercicio 2: Mediante while solicitar al usuario que ingrese un número entre 1 y 5. Si el número ingresado es 3 que imprima 'Usted ha ganado la loteria'

In [45]:
#Ejercicio 2
# Iniciar el bucle
while True:
    # Solicitar al usuario que ingrese un número entre 1 y 5
    numero = int(input("Ingrese un número entre 1 y 5: "))

    # Verificar si el número está dentro del rango permitido
    if numero < 1 or numero > 5:
        print("Número fuera del rango. Inténtelo nuevamente.")
    elif numero == 3:
        print("¡Usted ha ganado la lotería!")
        break  # Termina el bucle si el número es 3
    else:
        print(f"Usted ha ingresado el número {numero}. Inténtelo nuevamente.")


Ingrese un número entre 1 y 5: 5
Usted ha ingresado el número 5. Inténtelo nuevamente.
Ingrese un número entre 1 y 5: 4
Usted ha ingresado el número 4. Inténtelo nuevamente.
Ingrese un número entre 1 y 5: 3
¡Usted ha ganado la lotería!


Ejercicio 3: Crear una lista que contenga los valores desde 0 a 10. Luego solicitar que se ingrese un número entre 0 y 10. Imprimir en pantalla los valores de la lista hasta el número que ingresaron

In [50]:
#Ejercicio 3

lista_numeros = list(range(11))
numero = int(input("Ingrese un número entre 0 y 10: "))
if 0 <= numero <= 10:
    # Imprimimos los valores de la lista hasta el número ingresado
    print("Los números hasta el ingresado son:")
    for numero in lista_numeros[:numero+1]:  # Cortamos la lista hasta el índice ingresado
        print(numero)

Ingrese un número entre 0 y 10: 5
Los números hasta el ingresado son:
0
1
2
3
4
5


Ejercicio 4: Solicitar que se ingresen dos valores, mediante una función sumar estos dos numero y mostrar el resutaldo en pantalla

In [68]:
#Ejercicio 4
#Función
def multiplicar(numero1, numero2):
  return numero1*numero2


In [70]:
#Ejercicio 4

resultado = multiplicar(numero1, numero2)

numero1 = int(input("Ingrese un número "))
numero2 = int(input("Ingrese otro número "))
print("El resultado es: ", resultado)

Ingrese un número 5
Ingrese otro número 5
El resultado es:  25


Ejercicio 5: Solicitar que se ingresen dos valores, luego solicitar que tipo de operación se quiere realizar (suma, resta, multiplicación o división). Luego mediante una función realizar la operación matematica e imprimir el resultado.

In [71]:
#Ejercicio 5
#Función
def calculadora(a, b, operacion):
  if operacion == 'suma':
    return a + b
  elif operacion == 'resta':
    return a - b
  elif operacion == 'multiplicacion':
    return a * b
  elif operacion == 'division':
    return a / b
  else:
    return "Operación no válida"


In [72]:
#Ejercicio 5
a = int(input("Ingrese el primer numero: "))
b = int(input("Ingrese el segundo numero: "))
operacion = input("Ingrese la operación (suma, resta, multiplicacion, division): ")
resultado = calculadora(a, b, operacion)
print("El resultado de la operación es:", resultado)


Ingrese el primer numero: 5
Ingrese el segundo numero: 60
Ingrese la operación (suma, resta, multiplicacion, division): suma
El resultado de la operación es: 65
